### ISSUE TITLE
no lyrics at all load

### ISSUE THREAD

**Issue by daschenbrener** [tripod31/foo_lyricsource#1]
I cannot get any lyrics to load and get the

Failed to load DLL: foo_lyricsource.dll
Reason: This component is missing a required dependency, or was made for different version of foobar2000.

Any help is appreciated

**Comment by tripod31** [comment]
Hi.
please make sure:
Place these dll files to the directory that is containd in PATH enviromment,or the directory where foobar2000.exe resides.
libxml2.dll
iconv.dll

And I comfirmed it works,only on f2k version1.3.9.
I fixed access violation bug today,but maybe it does'nt relate to your case.

**Comment by daschenbrener** [comment]
I still get that error still and i have attached a screen show shoing i have those 2 dll's in the directory as well.
using 1.3.9 as well on windows 10
![foo error](https://cloud.githubusercontent.com/assets/15661340/11403875/67abb736-935c-11e5-9431-d4eb028e5160.png)

**Comment by daschenbrener** [comment]
works, thanks for your work
